- name: Copy virt-manager network definitions
  copy:
    src: "{{item}}"
    dest: "/tmp"
  with_items:
    - maas-net-admin.xml
    - maas-net-internal.xml
    - maas-net-oam.xml
    - maas-net-ext.xml
    - maas-net-k8s.xml
    - maas-net-public.xml

- name: Create bridges
  shell: |
    id=10
    # TODO: implement checks to avoid errors when re-creating an existing bridge
    for br in oam admin public internal ext k8s; do
      sudo brctl addbr maas-${br}
      sudo ifconfig maas-${br} 10.10.${id}.1/24 up

      sudo iptables -I FORWARD -s 10.10.${id}.0/24 -j ACCEPT
      sudo iptables -I FORWARD -d 10.10.${id}.0/24 -j ACCEPT
      sudo iptables -t nat -I POSTROUTING -s 10.10.${id}.0/24 -j MASQUERADE

      sudo virsh net-define /tmp/maas-net-${br}.xml
      sudo virsh net-start maas-${br}
      sudo virsh net-autostart maas-${br}
      id=$((id+10))
    done