- name: "Checkout virttools"
  git:
    repo: 'https://github.com/sombrafam/virt-tools.git'
    dest: /home/ubuntu/virt-tools
    clone: yes

- name: "Setup virt-tools"
  command: sh /home/ubuntu/virt-tools/kvm/setup_kvm_tools.sh

- name: "Download automaas image"
  get_url:
    dest: /home/ubuntu/VMStorage/Images/automaas-server-image.tar.xz
#   url: http://192.168.15.20/automaas-images/automaas-server-image.tar.xz
    url: https://people.canonical.com/~erlon/automaas-images/automaas-server-image.tar.xz
    tmp_dest: /home/ubuntu/VMStorage/Images
#   checksum: md5:http://192.168.15.20/automaas-images/automaas-server-image.tar.xz.md5
    checksum: md5:https://people.canonical.com/~erlon/automaas-images/automaas-server-image.tar.xz.md5
    mode: '0440'
    force: no

- name: Unpack MAAS image
  unarchive:
    src: /home/ubuntu/VMStorage/Images/automaas-server-image.tar.xz
    dest: /home/ubuntu/VMStorage/Disks/
    remote_src: yes
    creates: /home/ubuntu/VMStorage/Disks/vmdisk-automaas-server.qcow2

- name: "Create libvirt domain"
  shell: |
    #!/bin/bash -xe
    # TODO: Undefine if exists, so you can run the script
    # multiple times if something fails in the way.
    sudo virsh define /home/ubuntu/VMStorage/Disks/automaas-server.xml
    sudo virsh autostart automaas-server
    sudo virsh start automaas-server

- name: "Waiting for MAAS to became available"
  wait_for:
    host: 10.10.10.2
    port: 5240
    delay: 10


