- assert:
    that:
        - ansible_memtotal_mb >= {{ min_required_memory_mb }}
        - ansible_processor_vcpus >= {{ min_required_cpu }}
        - ansible_distribution_release == 'jammy'

- name: "Testing internet access"
  wait_for:
    host: github.com
    port: 22
    state: started
    delay: 1
    timeout: 10

# TODO: Pin package versions
- name: "Install the packages"
  become: true
  apt:
    name: [qemu-kvm, bridge-utils, maas-cli, jq]
    state: present
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: "Assure systemd-network is running"
  become: true
  service:
    name: systemd-networkd
    state: started

- name: "Assure lxd is running"
  become: true
  service:
    name: snap.lxd.daemon
    state: started

