- assert:
    that:
        - ansible_memtotal_mb >= 5000
        - ansible_processor_vcpus >= 2
        - ansible_distribution_release == 'bionic'

- name: "Testing internet access"
  wait_for:
    host: github.com
    port: 22
    state: started
    delay: 1
    timeout: 10

- name: "Install the packages"
  become: true
  apt:
    name: [virtinst, cloud-image-utils, qemu-kvm, cloud-image-utils,
    bridge-utils, libvirt-clients, libvirt-bin, maas-cli, jq]
    state: present
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: "Assure systemd-network is running"
  become: true
  service:
    name: systemd-networkd
    state: started

- name: "Assure libvirtd is running"
  become: true
  service:
    name: libvirt-bin
    state: started
