- assert:
    that:
        - ansible_memtotal_mb >= 5000
        - ansible_processor_vcpus >= 2
        - ansible_distribution_release == 'bionic'

- name: "Testing internet access"
  wait_for:
    host: github.com
    port: 22
    state: started
    delay: 1
    timeout: 10

# TODO: Pin package versions
- name: "Install the packages"
  become: true
  apt:
    name: [virtinst, cloud-image-utils, qemu-kvm, cloud-image-utils,
    bridge-utils, libvirt-clients, libvirt-bin, maas-cli, jq]
    state: present
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: "Assure systemd-network is running"
  become: true
  service:
    name: systemd-networkd
    state: started

- name: "Assure libvirtd is running"
  become: true
  service:
    name: libvirt-bin
    state: started

- name: "Enable password authentication"
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication yes'

- name: "Set password for user ubuntu"
  become: true
  lineinfile:
    path: /etc/shadow
    state: present
    regexp: '^ubuntu'
    line: 'ubuntu:$6$uHJKDSG68qu4WnSQ$Jz13SwqtOPSRaLanTqYAlMdTpORMrzYl.tnGgGNSNBVmXDsv7/t2ibC3j2kC6/GGDMUKvBcbcX.ks2it1alKR0:18592:0:99999:7:::'

- name: "Restart ssh service"
  become: true
  service:
    name: ssh
    state: restarted
