- name: "Printing access addresses"
  debug:
    msg: "You can access the MAAS server in http://{{ ansible_ssh_host }}:5240/MAAS Credentials are admin -> admin"

- name: "Printing credentials"
  debug:
    msg: "Credentials are admin -> admin"

# TODO: Inject user public keys into maas server and MAAS keys
- name: "Printing credentials"
  debug:
    msg: "SSH access to MAAS server is: ssh -p 2222 ubuntu@{{ ansible_ssh_host }}"

# Implemente a better logic, if possible parametrized to create VMs
- name: "Creating 6 VMs"
  shell: |
    #!/bin/bash
    /home/ubuntu/bin/spawn-vm --name {{ item }} --vcpus 2 --mem 8192 --disk 60  --maas --series bionic
  with_items:
    - small-vm-01
    - small-vm-02
    - small-vm-03
    - small-vm-04
    - small-vm-05
    - small-vm-06

- name: "Waiting VMs to boot and enlist to MAAS"
  shell: |
    #!/bin/bash
    timeout=300
    while [[ timeout -gt 0 ]]; do
        virsh dominfo {{ item }} | grep -E 'shut off'
        if [[ $? == 0 ]]; then
            continue
        else
            echo "VM {{ item }} not ready yet, waiting 5 more sec"
            timeout=$((timeout - 5))
            sleep 5
        fi
    done
  with_items:
    - small-vm-01
    - small-vm-02
    - small-vm-03
    - small-vm-04
    - small-vm-05
    - small-vm-06

